# ===================================================================
# SECURITY UPDATE: Credentials externalized to Environment Variables
# Prevented hardcoded sensitive data vulnerability.
# ===================================================================
spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    # If the DATABASE_USER variable does not exist in Windows, Spring falls back to 'root' as default
    url: ${URL_DB}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false

    open-in-view: false