apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ${DATABASE_DOCKER_ROOT_PASS}
  MYSQL_USER: ${DATABASE_DOCKER_USER}
  MYSQL_PASSWORD: ${DATABASE_DOCKER_PASS}